Update full-installation.rst
Error: Package: tuleap-8.4.99.55-1.el6.noarch (Tuleap)
Requires: vixie-cron >= 4.1-9

(besides that a minimal OS install also complains about: libpython, perl-suidperl, perl, mysql-server and mod_auth_mysql).